name: Metrics for ferferga
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    name: Generate 🛠
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: 📊 Personal metrics (left)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          user: ferferga
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          base_hireable: yes
          config_timezone: Europe/Madrid
          config_twemoji: yes
          plugin_gists: yes
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_ignored: TSQL
          plugin_languages_limit: 0
          plugin_languages_threshold: 0%
          #plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 15
          plugin_languages_recent_load: 1000
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_recent_days: 30
          commits_authoring: ${{ secrets.COMMIT_SIGNATURES }}
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: repositories
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          # plugin_traffic: yes - Disabled due to lack of access to org repos I own. TODO: Fix upstream so errors in this plugin can be ignored
          plugins_errors_fatal: yes
          repositories: 99999999999999999999999
          repositories_affiliations: ""
          verify: yes
          output_action: none
          optimize: yes
          retries: 10
          retries_delay: 300
          filename: ferferga-metrics_left.svg

      - name: 📊 Personal metrics (right)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          base: ''
          base_indepth: yes
          user: ferferga
          template: classic
          config_timezone: Europe/Madrid
          config_twemoji: yes
          config_display: columns
          config_order: sponsors, achievements
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugins_errors_fatal: yes
          repositories: 99999999999999999999999
          repositories_affiliations: ""
          plugin_sponsors: yes
          plugin_sponsors_sections: goal, list
          plugin_sponsors_past: yes
          verify: yes
          output_action: none
          optimize: yes
          retries: 10
          retries_delay: 300
          filename: ferferga-metrics_right.svg
          config_padding: 0, 220px

      - name: Move output to working directory
        run: sudo mv /metrics_renders/ferferga-metrics_* .

        # "echo" returns true so the build succeeds, even if no changed files
      - name: Commit to the repo
        run: |
          git config --global user.name "Fernando Fernández"
          git config --global user.email "ferferga@hotmail.com"
          git add ferferga-metrics_*
          git commit --amend --no-edit || echo
          git push -f
